# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2020 Caidy
# Author: Chen Caidy <chen@caidy.cc>

obj-y += openvfd.o
openvfd-objs += protocols/i2c_sw.o
openvfd-objs += protocols/spi_sw.o
openvfd-objs += controllers/dummy.o
openvfd-objs += controllers/seg7_ctrl.o
openvfd-objs += controllers/fd628.o
openvfd-objs += controllers/fd650.o
openvfd-objs += openvfd_drv.o
